app:
    path: /
    defaults: { _controller:AppBundle:Default:index}

saludopersonal:
    path: /hello/{name}
    defaults: { _controller:AppBundle:hello:saludo}

saludo:
    path: /hello
    defaults: { _controller:AppBundle:hello:fijo}
